# Generated by Django 5.2.6 on 2025-09-29 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='EtapaEscolar',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_etapa', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
            ],
            options={
                'verbose_name': 'Etapa Escolar',
                'verbose_name_plural': 'Etapas Escolares',
                'db_table': 'Etapa_Escolar',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='StatusEnvio',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_status', models.CharField(max_length=100, verbose_name='Descrição do Status')),
            ],
            options={
                'verbose_name': 'Status de Envio',
                'verbose_name_plural': 'Status de Envio',
                'db_table': 'Status_Envio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100, verbose_name='Nome do Usuário')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('id_perfil', models.ForeignKey(db_column='Id_Perfil', on_delete=django.db.models.deletion.CASCADE, to='api.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='EnvioMaterial',
            fields=[
                ('created_by', models.CharField(default=None, max_length=100, verbose_name='Criado por')),
                ('updated_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('deleted_by', models.CharField(default=None, max_length=100, verbose_name='Atualizado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado em')),
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('mes_referencia', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês de Referência')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('observacoes_gerencia', models.TextField(blank=True, null=True, verbose_name='Observações da Gerência')),
                ('data_envio_escola', models.DateField(blank=True, null=True, verbose_name='Data de Envio da Escola')),
                ('data_envio_see', models.DateField(blank=True, null=True, verbose_name='Data de Envio SEE')),
                ('data_validacao_gerencia', models.DateField(blank=True, null=True, verbose_name='Data de Validação da Gerência')),
                ('data_envio_formador', models.DateField(blank=True, null=True, verbose_name='Data de Envio ao Formador')),
                ('data_limite_envio', models.DateField(blank=True, null=True, verbose_name='Data Limite de Envio')),
                ('id_disciplina', models.ForeignKey(db_column='Id_Disciplina', on_delete=django.db.models.deletion.CASCADE, to='api.disciplina', verbose_name='Disciplina')),
                ('id_etapa', models.ForeignKey(db_column='Id_Etapa', on_delete=django.db.models.deletion.CASCADE, to='api.etapaescolar', verbose_name='Etapa Escolar')),
                ('id_status', models.ForeignKey(db_column='Id_Status', on_delete=django.db.models.deletion.CASCADE, to='api.statusenvio', verbose_name='Status')),
                ('id_usuario', models.ForeignKey(db_column='Id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Envio de Material',
                'verbose_name_plural': 'Envios de Material',
                'db_table': 'Envio_material',
                'unique_together': {('id_etapa', 'id_disciplina', 'id_usuario', 'mes_referencia', 'ano_referencia')},
            },
        ),
    ]
