# Generated by Django 5.2.6 on 2025-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='etapaescolar',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='etapaescolar',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='etapaescolar',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='statusenvio',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='statusenvio',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='statusenvio',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
    ]
