# Generated by Django 5.2.6 on 2025-10-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviomaterial',
            name='ano_referencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Referência'),
        ),
    ]
