# Generated by Django 5.2.6 on 2025-10-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enviomaterial_ano_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviomaterial',
            name='id_status',
            field=models.ForeignKey(db_column='Id_Status', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.statusenvio', verbose_name='Status'),
        ),
    ]
