# Generated by Django 5.2.6 on 2025-10-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enviomaterial_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviomaterial',
            name='ano_referencia',
            field=models.IntegerField(default=2025, verbose_name='Ano de Referência'),
        ),
    ]
