# Generated by Django 5.2.6 on 2025-10-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enviomaterial_ano_referencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enviomaterial',
            unique_together=set(),
        ),
    ]
