# Generated by Django 5.2.6 on 2025-10-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_enviomaterial_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='id_perfil',
            new_name='id',
        ),
    ]
