# Generated by Django 5.2.6 on 2025-10-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_perfil_perfil_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
