# Generated by Django 5.2.6 on 2025-10-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_id_usuario_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapaescolar',
            old_name='id_etapa',
            new_name='id',
        ),
    ]
