# Generated by Django 5.2.6 on 2025-10-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_etapa_etapaescolar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='id_disciplina',
            new_name='id',
        ),
    ]
