# Generated by Django 5.2.6 on 2025-10-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_id_disciplina_disciplina_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusenvio',
            old_name='id_status',
            new_name='id',
        ),
    ]
