# Generated by Django 5.2.6 on 2025-10-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_id_status_statusenvio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviomaterial',
            old_name='id_envio',
            new_name='id',
        ),
    ]
